<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <ProjectReference Include="..\HoverText.Core\HoverText.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ApplicationIcon>Assets\hovertext.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\hovertext.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\hovertext-icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
